# reports.py
import datetime
import os
from config import OUTPUT_FILENAME, RISK_LEVELS

def generate_markdown_report(findings: list) -> str:
    """
    Generates a Markdown report from the list of findings.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = "# Linux Security Commands Audit Report\n\n"
    content += f"**Audit Date:** {timestamp}\n\n"
    content += "---\n\n"
    
    content += "## Summary of Findings\n"
    
    # Count statuses
    counts = {"PASS": 0, "FAIL": 0, "INFO": 0, "ERROR": 0}
    for f in findings:
        counts[f["status"]] += 1
        
    content += f"- **Total Checks:** {len(findings)}\n"
    content += f"- **Passed:** {counts['PASS']} 🟢\n"
    content += f"- **Failed:** {counts['FAIL']} 🔴\n"
    content += f"- **Info/Manual Review:** {counts['INFO']} 🔵\n"
    content += f"- **Errors:** {counts['ERROR']} ⚠️\n\n"
    
    content += "---\n\n"
    content += "## Detailed Results\n\n"
    
    # Group by category
    categories = {}
    for f in findings:
        cat = f["category"]
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(f)
        
    for cat, items in categories.items():
        content += f"### {cat}\n\n"
        for item in items:
            risk = RISK_LEVELS.get(item["risk_level"], item["risk_level"])
            
            content += f"#### [{item['status']}] {item['name']}\n"
            content += f"- **Risk Level:** {risk}\n"
            content += f"- **Description:** {item['description']}\n"
            content += f"- **Command Run:** `{item['command']}`\n"
            
            if item['status'] == 'FAIL':
                content += f"- **Issue:** {item['notes']}\n"
                content += f"- **Remediation:** {item['remediation']}\n"
            elif item['status'] == 'ERROR':
                content += f"- **Error Detail:** {item['notes']}\n"
            elif item['status'] == 'INFO':
                content += f"- **Notes:** {item['notes']}\n"
                
            if item['raw_output']:
                content += "\n<details><summary><b>View Raw Output</b></summary>\n\n```text\n"
                content += item['raw_output']
                content += "\n```\n</details>\n"
                
            content += "\n"
            
    content += "---\n"
    content += "*Disclaimer: This report was generated by an educational and defensive auditing tool. It does not constitute a full penetration test.*"
    
    with open(OUTPUT_FILENAME, 'w', encoding='utf-8') as f:
        f.write(content)
        
    return os.path.abspath(OUTPUT_FILENAME)
